parameters:

services:
  api.command.dbUp:
    class: Velocity\Bundle\ApiBundle\Command\DbUpCommand
    arguments:
      - @api.migration
    tags:
      - { name: console.command }
  api.command.dbDrop:
    class: Velocity\Bundle\ApiBundle\Command\DbDropCommand
    arguments:
      - @api.database
    tags:
      - { name: console.command }
