parameters:

services:
  api.command.dbUp:
    class: Velocity\Bundle\ApiBundle\Command\DbUpCommand
    calls:
      - [setMigrationService, [@velocity.migration]]
    tags:
      - { name: console.command }
  api.command.dbDrop:
    class: Velocity\Bundle\ApiBundle\Command\DbDropCommand
    calls:
      - [setDatabaseService, [@velocity.database]]
    tags:
      - { name: console.command }
  api.command.businessRuleList:
    class: Velocity\Bundle\ApiBundle\Command\BusinessRuleListCommand
    calls:
      - [setBusinessRuleService, [@velocity.businessRule]]
    tags:
      - { name: console.command }
