parameters:

services:
  api.command.dbUp:
    class: Velocity\Bundle\ApiBundle\Command\DbUpCommand
    calls:
      - [setMigrationService, [@api.migration]]
    tags:
      - { name: console.command }
  api.command.dbDrop:
    class: Velocity\Bundle\ApiBundle\Command\DbDropCommand
    calls:
      - [setDatabaseService, [@api.database]]
    tags:
      - { name: console.command }
