services:
  velocity.eventAction.addVar:
    class: Velocity\Bundle\ApiBundle\EventAction\AddVarEventAction
    arguments:
      - @service_container
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.call:
    class: Velocity\Bundle\ApiBundle\EventAction\CallEventAction
    arguments:
      - @service_container
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.businessRule:
    class: Velocity\Bundle\ApiBundle\EventAction\BusinessRuleEventAction
    arguments:
      - @velocity.businessRule
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.exception:
    class: Velocity\Bundle\ApiBundle\EventAction\ExceptionEventAction
    tags:
      - { name: "velocity.event_action" }
