services:
  velocity.eventAction.addVar:
    class: Velocity\Bundle\ApiBundle\EventAction\AddVarEventAction
    arguments:
      - @service_container
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.call:
    class: Velocity\Bundle\ApiBundle\EventAction\CallEventAction
    arguments:
      - @service_container
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.businessRule:
    class: Velocity\Bundle\ApiBundle\EventAction\BusinessRuleEventAction
    arguments:
      - @velocity.businessRule
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.exception:
    class: Velocity\Bundle\ApiBundle\EventAction\ExceptionEventAction
    tags:
      - { name: "velocity.event_action" }
  velocity.eventAction.alter:
    class: Velocity\Bundle\ApiBundle\EventAction\AlterEventAction
    tags:
      - { name: velocity.event_action }
      - { name: velocity.repositories_aware }
  velocity.eventAction.auditLog:
    class: Velocity\Bundle\ApiBundle\EventAction\AuditLogEventAction
    arguments:
      - @security.token_storage
      - @event_dispatcher
    tags:
      - { name: velocity.event_action }
  velocity.eventAction.log:
    class: Velocity\Bundle\ApiBundle\EventAction\LogEventAction
    arguments:
      - @logger
    tags:
      - { name: velocity.event_action }
