services:
  api.security.provider.user.api:
    class: Velocity\Bundle\ApiBundle\Security\ApiUserProvider

  api.security.authentication.provider:
    class: Velocity\Bundle\ApiBundle\Security\ApiAuthenticationProvider
    arguments:
      - @api.security.provider.user.api
    calls:
      - [setEventDispatcher, [@event_dispatcher]]
      - [setRequestService, [@api.request]]
  api.security.authentication.listener:
    class: Velocity\Bundle\ApiBundle\Security\ApiListener
    arguments:
      - @security.context
      - @security.authentication.manager
    calls:
      - [setEventDispatcher, [@event_dispatcher]]
      - [setRequestService, [@api.request]]
