services:
  velocity.security.provider.user.api:
    class: Velocity\Bundle\ApiBundle\Security\ApiUserProvider

  velocity.security.authentication.provider:
    class: Velocity\Bundle\ApiBundle\Security\ApiAuthenticationProvider
    arguments:
      - @velocity.security.provider.user.api
    calls:
      - [setEventDispatcher, [@event_dispatcher]]
      - [setRequestService, [@velocity.request]]
  velocity.security.authentication.listener:
    class: Velocity\Bundle\ApiBundle\Security\ApiListener
    arguments:
      - @security.token_storage
      - @security.authentication.manager
    calls:
      - [setEventDispatcher, [@event_dispatcher]]
      - [setRequestService, [@velocity.request]]
