services:
  api.validator.mongoId:
        class: Velocity\Bundle\ApiBundle\Validator\Constraints\MongoIdValidator
        tags:
          - { name: validator.constraint_validator, alias: api_mongoId }