services:
  api.metadata:
    class: %api_ns%\Service\MetaDataService
  api.exception:
    class: %api_ns%\Service\ExceptionService
    arguments:
      - @request_stack
      - @api.form
  api.supervision:
    class: %api_ns%\Service\SupervisionService
    arguments:
      - @security.context
  api.request:
    class: %api_ns%\Service\RequestService
    arguments:
      - @api.security.provider.user.api
      - @app.client
      - %app_security_client_secret%
      - %app_security_user_secret%
  api.mongo:
    class: MongoClient
    arguments:
      - %app_mongo_server%
  api.database:
    class: %api_ns%\Service\DatabaseService
    arguments:
      - @api.mongo
      - @logger
      - @api.form
      - @service_container
    calls:
      - [setCollectionName, ['migration']]
      - [setDatabaseName, ["%app_mongo_db%"]]
      - [setEnvironment, ["%app_env%"]]
      - [setDirectory, ["%app_db_dir%"]]
  api.form:
    class: %api_ns%\Service\FormService
    arguments:
      - @form.factory
