services:
  api.metadata:
    class: Velocity\Bundle\ApiBundle\Service\MetaDataService
  api.exception:
    class: Velocity\Bundle\ApiBundle\Service\ExceptionService
    arguments:
      - @request_stack
      - @api.form
  api.supervision:
    class: Velocity\Bundle\ApiBundle\Service\SupervisionService
    arguments:
      - @security.context
  api.math:
    class: Velocity\Bundle\ApiBundle\Service\MathService
  api.request:
    class: Velocity\Bundle\ApiBundle\Service\RequestService
    arguments:
      - @api.security.provider.user.api
      - @app.client
      - %app.security.client.secret%
      - %app.security.user.secret%
  api.mongo:
    class: MongoClient
    arguments:
      - %app.mongo.server%
  api.database:
    class: Velocity\Bundle\ApiBundle\Service\DatabaseService
    arguments:
      - @api.mongo
      - %app.mongo.db%
  api.migration:
    class: Velocity\Bundle\ApiBundle\Service\MigrationService
    arguments:
      - @api.database
      - @logger
      - @api.form
      - @service_container
      - 'migration'
      - %app.db.dir%
      - %app.env%
  api.form:
    class: Velocity\Bundle\ApiBundle\Service\FormService
    arguments:
      - @form.factory
