services:
  velocity.metadata:
    class: Velocity\Bundle\ApiBundle\Service\MetaDataService
  velocity.exception:
    class: Velocity\Bundle\ApiBundle\Service\ExceptionService
    arguments:
      - @request_stack
      - @velocity.form
  velocity.supervision:
    class: Velocity\Bundle\ApiBundle\Service\SupervisionService
    arguments:
      - @security.context
  velocity.math:
    class: Velocity\Bundle\ApiBundle\Service\MathService
  velocity.date:
    class: Velocity\Bundle\ApiBundle\Service\DateService
  velocity.request:
    class: Velocity\Bundle\ApiBundle\Service\RequestService
    arguments:
      - @velocity.security.provider.user.api
      - %app_security_client_secret%
      - %app_security_user_secret%
  velocity.factory:
    class: Velocity\Bundle\ApiBundle\Service\ServiceFactoryService
  velocity.mangoPayApi:
    class: MangoPay\MangoPayApi
    factory_service: velocity.factory
    factory_method: createMangoPayApi
    arguments:
      - %app_mango_env%
      - %app_mango_client_id%
      - %app_mango_client_password%
  velocity.mangoPay:
    class: Velocity\Bundle\ApiBundle\Service\MangoPayService
    arguments:
      - @velocity.mangoPayApi
  velocity.mongo:
    class: MongoClient
    arguments:
      - %app_mongo_server%
  velocity.database:
    class: Velocity\Bundle\ApiBundle\Service\DatabaseService
    arguments:
      - @velocity.mongo
      - %app_mongo_db%
      - %app_mongo_db_random%
  velocity.migration:
    class: Velocity\Bundle\ApiBundle\Service\MigrationService
    arguments:
      - @velocity.database
      - @logger
      - @velocity.form
      - @service_container
      - 'migration'
      - %app_db_dir%
      - %app_env%
  velocity.form:
    class: Velocity\Bundle\ApiBundle\Service\FormService
    arguments:
      - @form.factory
  velocity.password:
    class: Velocity\Bundle\ApiBundle\Service\PasswordService
  velocity.eventAction:
    class: Velocity\Bundle\ApiBundle\Service\EventActionService
  velocity.businessRule:
    class: Velocity\Bundle\ApiBundle\Service\BusinessRuleService
  velocity.generator:
    class: Velocity\Bundle\ApiBundle\Service\GeneratorService
  velocity.attachment:
    class: Velocity\Bundle\ApiBundle\Service\AttachmentService
    arguments:
      - @velocity.generator
  velocity.twig.extension.velocity:
    class: Velocity\Bundle\ApiBundle\Twig\ApiExtension
    arguments:
      - %app_variables%
    tags:
      - {name: twig.extension}

