services:
  api.metadata:
    class: Velocity\Bundle\ApiBundle\Service\MetaDataService
  api.exception:
    class: Velocity\Bundle\ApiBundle\Service\ExceptionService
    arguments:
      - @request_stack
      - @api.form
  api.supervision:
    class: Velocity\Bundle\ApiBundle\Service\SupervisionService
    arguments:
      - @security.context
  api.math:
    class: Velocity\Bundle\ApiBundle\Service\MathService
  api.date:
    class: Velocity\Bundle\ApiBundle\Service\DateService
  api.request:
    class: Velocity\Bundle\ApiBundle\Service\RequestService
    arguments:
      - @api.security.provider.user.api
      - %app_security_client_secret%
      - %app_security_user_secret%
  api.factory:
    class: Velocity\Bundle\ApiBundle\Service\ServiceFactoryService
  api.mangoPayApi:
    class: MangoPay\MangoPayApi
    factory_service: api.factory
    factory_method: createMangoPayApi
    arguments:
      - %app_mango_env%
      - %app_mango_client_id%
      - %app_mango_client_password%
  api.mangoPay:
    class: Velocity\Bundle\ApiBundle\Service\MangoPayService
    arguments:
      - @api.mangoPayApi
  api.mongo:
    class: MongoClient
    arguments:
      - %app_mongo_server%
  api.database:
    class: Velocity\Bundle\ApiBundle\Service\DatabaseService
    arguments:
      - @api.mongo
      - %app_mongo_db%
  api.migration:
    class: Velocity\Bundle\ApiBundle\Service\MigrationService
    arguments:
      - @api.database
      - @logger
      - @api.form
      - @service_container
      - 'migration'
      - %app_db_dir%
      - %app_env%
  api.form:
    class: Velocity\Bundle\ApiBundle\Service\FormService
    arguments:
      - @form.factory
  api.password:
    class: Velocity\Bundle\ApiBundle\Service\PasswordService

