services:
  velocity.action.addvar:
    class: Velocity\Bundle\ApiBundle\Action\AddVarAction
    arguments:
      - @service_container
    tags:
      - { name: velocity.action }
  velocity.action.call:
    class: Velocity\Bundle\ApiBundle\Action\CallAction
    arguments:
      - @service_container
    tags:
      - { name: velocity.action }
  velocity.action.businessrule:
    class: Velocity\Bundle\ApiBundle\Action\BusinessRuleAction
    arguments:
      - @velocity.businessrule
    tags:
      - { name: velocity.action }
  velocity.action.exception:
    class: Velocity\Bundle\ApiBundle\Action\ExceptionAction
    tags:
      - { name: velocity.action }
  velocity.action.alter:
    class: Velocity\Bundle\ApiBundle\Action\AlterAction
    tags:
      - { name: velocity.action }
      - { name: velocity.repositories_aware }
  velocity.action.auditlog:
    class: Velocity\Bundle\ApiBundle\Action\AuditLogAction
    arguments:
      - @security.token_storage
      - @event_dispatcher
    tags:
      - { name: velocity.action }
  velocity.action.archivedoc:
    class: Velocity\Bundle\ApiBundle\Action\ArchiveDocAction
    arguments:
      - @velocity.archiver
    tags:
      - { name: velocity.action }
  velocity.action.job:
    class: Velocity\Bundle\ApiBundle\Action\JobAction
    arguments:
      - @velocity.job
    tags:
      - { name: velocity.action }
  velocity.action.batch:
    class: Velocity\Bundle\ApiBundle\Action\BatchAction
    arguments:
      - @velocity.batch
    tags:
      - { name: velocity.action }
  velocity.action.log:
    class: Velocity\Bundle\ApiBundle\Action\LogAction
    arguments:
      - @logger
    tags:
      - { name: velocity.action }
  velocity.action.context:
    class: Velocity\Bundle\ApiBundle\Action\ContextAction
    tags:
      - { name: velocity.action }
  velocity.action.letter:
    class: Velocity\Bundle\ApiBundle\Action\LetterAction
    arguments:
      - @templating
      - @translator
      - @velocity.attachment
      - @event_dispatcher
      - %app_senders%
      - %app_recipients%
      - %app_env%
      - @request_stack
      - %app_tenant%
      - %locale%
    tags:
      - { name: velocity.action }
  velocity.action.mail:
    class: Velocity\Bundle\ApiBundle\Action\MailAction
    arguments:
      - @templating
      - @translator
      - @velocity.attachment
      - @event_dispatcher
      - %app_senders%
      - %app_recipients%
      - %app_env%
      - @request_stack
      - %app_tenant%
      - %locale%
    tags:
      - { name: velocity.action }
  velocity.action.sms:
    class: Velocity\Bundle\ApiBundle\Action\SmsAction
    arguments:
      - @templating
      - @translator
      - @velocity.attachment
      - @event_dispatcher
      - %app_senders%
      - %app_recipients%
      - %app_env%
      - @request_stack
      - %app_tenant%
      - %locale%
    tags:
      - { name: velocity.action }
  velocity.action.fax:
    class: Velocity\Bundle\ApiBundle\Action\FaxAction
    arguments:
      - @templating
      - @translator
      - @velocity.attachment
      - @event_dispatcher
      - %app_senders%
      - %app_recipients%
      - %app_env%
      - @request_stack
      - %app_tenant%
      - %locale%
    tags:
      - { name: velocity.action }
  velocity.action.fire:
    class: Velocity\Bundle\ApiBundle\Action\FireAction
    arguments:
      - @event_dispatcher
    tags:
      - { name: velocity.action }
  velocity.action.generate:
    class: Velocity\Bundle\ApiBundle\Action\GenerateAction
    arguments:
      - @velocity.generator
      - @velocity.storage
    tags:
      - { name: velocity.action }
  velocity.action.storage:
    class: Velocity\Bundle\ApiBundle\Action\StorageAction
    arguments:
      - @velocity.storage
    tags:
      - { name: velocity.action }
  velocity.action.documentBuilder:
    class: Velocity\Bundle\ApiBundle\Action\DocumentBuilderAction
    arguments:
      - @velocity.documentBuilder
    tags:
      - { name: velocity.action }
