services:
  velocity.listener.request:
    class: Velocity\Bundle\ApiBundle\Listener\RequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
  velocity.listener.exception:
    class: Velocity\Bundle\ApiBundle\Listener\ExceptionListener
    arguments:
      - @velocity.response
      - @request_stack
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
