services:
  velocity.migrator.php:
    class: Velocity\Bundle\ApiBundle\Migrator\PhpMigrator
    calls:
      - [setEventDispatcher, [@event_dispatcher]]
    tags:
      - {name: velocity.migrator, extension: php}
  velocity.migrator.yaml:
    class: Velocity\Bundle\ApiBundle\Migrator\YamlMigrator
    tags:
      - {name: velocity.migrator, extension: yaml}
