services:
  velocity.validator.mongo_id:
        class: Velocity\Bundle\ApiBundle\Validator\Constraints\MongoIdValidator
        tags:
          - { name: validator.constraint_validator, alias: velocity_mongo_id }
