services:
  velocity.validator.mongoId:
        class: Velocity\Bundle\ApiBundle\Validator\Constraints\MongoIdValidator
        tags:
          - { name: validator.constraint_validator, alias: velocity_mongoId }
