services:
  velocity.typeGuesser.enum:
    class: Velocity\Bundle\ApiBundle\Form\TypeGuesser\EnumTypeGuesser
    arguments:
      - @velocity.metaData
    tags:
      - { name: form.type_guesser }
  velocity.typeGuesser.referenceList:
    class: Velocity\Bundle\ApiBundle\Form\TypeGuesser\ReferenceListTypeGuesser
    arguments:
      - @velocity.metaData
    tags:
      - { name: form.type_guesser }
  velocity.typeGuesser.workflow:
    class: Velocity\Bundle\ApiBundle\Form\TypeGuesser\WorkflowTypeGuesser
    arguments:
      - @velocity.metaData
    tags:
      - { name: form.type_guesser }
